name: Deploy via Github Pages
on:
  push:
    branches: [master]
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
          VITE_REPO_OWNER: ${{ github.repository_owner }}
          VITE_REPO_NAME: ${{ github.event.repository.name }}
          VITE_GITHUB_BRANCH: master

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4